# Purview Panda mk_deployment-config.yaml
defaults:
  verification:
    timeout: 30000
    httpTimeout: 10000
    cleanupVerificationFile: true
    retries: 3
    retryDelay: 2000
  excludes:
    - '*.tmp'
    - '*.log'
    - '.git/**'
    - '.gitignore'
    - 'README.md'
    - 'node_modules/**'
    - 'assets/images/**'
    - 'assets/img/**'
    # per-part media handled below
    - '.env*'
    - 'deployment-*'
    - 'AUTO-DEPLOY-MK/**'
    - '_backup*/**'
    - '_documentation/**'
    - '_deployment-system/**'
    - '.htaccess'

targets:
  # Primary prod target for purviewpanda.de
  production_purview:
    method: ftp
    # Use FTP root here; map projects to full domain paths in their parts to avoid duplication
    remoteRoot: '/'
    domain: 'purviewpanda.de'
    ftp:
      host: '${FTP_HOST}'
      user: '${FTP_USER}'
      password: '${FTP_PASSWORD}'
      timeout: 30000

  local:
    method: copy
    localPath: './httpdocs-local'
    domain: 'localhost:5000'

projects:
  web:
    # main public site under httpdocs
    localSource: './httpdocs'
    localBuild: './httpdocs'
    buildCommand: '' # no build step for static httpdocs assets here
    parts:
      default:
        include:
          - '**/*'
        exclude:
          - 'admin/**' # admin handled by separate part
          - 'deploy-verify-*.html' # generated by tool
          - 'uploads/**'
          - 'img/**'
          - 'audio/**'
        remotePath: '/httpdocs'
        webPath: '/'
      media:
        # Full static media set; deploy together with default when a full publish is needed
        include:
          - 'uploads/**'
          - 'img/**'
          - 'audio/**'
        remotePath: '/httpdocs'
        webPath: '/'
    verify:
      enabled: true
      fileTemplate: 'deploy-verify-{timestamp}.html'
      urlTemplate: 'https://{domain}/{file}'

  server:
    localSource: '.'
    localBuild: '.'
    buildCommand: ''
    parts:
      default:
        # special fixed mappings for backend files when needed (example only, disabled by default)
        include: []
        files:
          - from: 'package.json'
            to: '/package.json'
          - from: 'server.js'
            to: '/server.js'
        remotePath: '/'
        webPath: '/'
    verify:
      enabled: false

  admin:
    # admin center lives under httpdocs/admin
    localSource: './httpdocs/admin'
    localBuild: './httpdocs/admin'
    buildCommand: '' # adjust if admin has its own build
    parts:
      default:
        include:
          - '**/*'
        # admin lives under httpdocs/admin within the domain folder
        remotePath: '/httpdocs/admin'
        webPath: '/admin'
    verify:
      enabled: false

  backend:
    # main app code + views at domain root
    localSource: '.'
    localBuild: '.'
    buildCommand: ''
    parts:
      # Deploy small batches to avoid FTP dropouts on shared hosting
      core:
        include:
          - 'server.js'
          - 'db.js'
          - 'i18n.js'
          - 'migrate.js'
        files:
          - from: '.env'
            to: '/.env'
          - from: 'package.json'
            to: '/package.json'
          - from: 'tmp/restart.txt'
            to: '/tmp/restart.txt'
          - from: 'tmp/restart.txt'
            to: '/httpdocs/tmp/restart.txt'
        remotePath: '/'
        webPath: '/'
      lib:
        include:
          - 'lib/**'
        remotePath: '/'
        webPath: '/'
      routes:
        include:
          - 'routes/**'
        remotePath: '/'
        webPath: '/'
      views:
        include:
          - 'views/**'
        remotePath: '/'
        webPath: '/'
      locales:
        include:
          - 'locales/**'
        remotePath: '/'
        webPath: '/'
      scripts:
        include:
          - 'scripts/**'
        remotePath: '/'
        webPath: '/'
      config:
        include:
          - 'config/**'
        remotePath: '/'
        webPath: '/'
      restart:
        include: []
        files:
          - from: 'tmp/restart.txt'
            to: '/tmp/restart.txt'
          - from: 'tmp/restart.txt'
            to: '/httpdocs/tmp/restart.txt'
        remotePath: '/'
        webPath: '/'
      # Keep the original 'default' as an all-in-one option if ever needed
      default:
        include:
          - 'server.js'
          - 'db.js'
          - 'i18n.js'
          - 'migrate.js'
          - 'lib/**'
          - 'routes/**'
          - 'views/**'
          - 'locales/**'
        files:
          - from: '.env'
            to: '/.env'
          - from: 'package.json'
            to: '/package.json'
          - from: 'tmp/restart.txt'
            to: '/tmp/restart.txt'
          - from: 'tmp/restart.txt'
            to: '/httpdocs/tmp/restart.txt'
        remotePath: '/'
        webPath: '/'
    verify:
      enabled: false
# End of configuration
